version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym_server
    ports:
      - "8080:80" #Use 8080 for the host, but the container still runs on port 80
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver22;Database=GymManagementSystem;User Id=sa;Password=t01UA<2%7~v4;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:80
    restart: always
    networks:
      - dotnet_gym

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver22
    hostname: sqlserver22
    environment:
      MSSQL_SA_PASSWORD: "t01UA<2%7~v4"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: "1433"
      MSSQL_DATA_DIR: /var/opt/mssql/data
    ports:
      - "1433:1433"
    restart: always
    volumes:
      # - sqlserver_data:/var/opt/mssql
      - /etc/mssql22/data:/var/opt/mssql/data
      - /etc/mssql22/log:/var/opt/mssql/log
      - /etc/mssql22/secrets:/var/opt/mssql/secrets
    networks:
      - dotnet_gym

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"  # Add HTTPS support
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always
    networks:
      - dotnet_gym

# volumes:
#   sqlserver_data:

networks:
  dotnetgym:
    driver: bridge