version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gym_server
    ports:
      - "8080:80" #Use 8080 for the host, but the container still runs on port 80
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=GymManagementSystem;User Id=sa;Password=t01UA<2%7~v4;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:80
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "t01UA<2%7~v4"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always

volumes:
  sqlserver_data:
